name: 🐞 Internal Testing Bug
description: File a bug/issue as a result of internal testing
title: 'Issue Title'
labels: ["bug", "needs-triage", "internal-testing"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: markdown
  attributes:
    value: |
      ## Bug Severity and Priority
      Please self -assess the severity and priority of this bug based on the definitions below:

      ### Severity Levels:
      - **Sev 1 - Critical**: The bug causes a complete loss of service or a critical feature is broken for all users.
      - **Sev 2 - High**: The bug significantly impairs functionality or performance for a large number of users.
      - **Sev 3 - Medium**: The bug affects a feature or functionality but has a workaround available.
      - **Sev 4 - Low**: The bug is minor and does not significantly impact user experience.

      ### Priority Levels:
      - **P0 - Blocker**: Requires immediate attention and resolution.
      - **P1 - High**: Should be addressed in the next development cycle.
      - **P2 - Medium**: Can be scheduled for a future development cycle.
      - **P3 - Low**: Can be addressed at a later time or as part of routine maintenance.

- type: dropdown
  id: severity
  attributes:
    label: What is the impact of this bug?
    description: Select the severity level of the bug.
    options:
        - Sev 1 Critical
        - Sev 2 High
        - Sev 3 Medium
        - Sev 4 Low
  validations:
    required: true
- type: dropdown
  id: priority
  attributes:
    label: What is the priority of this bug?
    description: Select the priority level for addressing the bug.
    options:
        - P0 Blocker
        - P1 High
        - P2 Medium
        - P3 Low
  validations:
    required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      1. With this config...
      1. Run '...'
      1. See error...
  validations:
    required: true
- type: textarea
  attributes:
    label: Screenshots or Screen Captures
    description: Add screenshots or screen captures for added context
    value: |
      <details>
        <summary>
          Screenshots Bellow
        </summary>
        ![Screenshot](url-to-screenshot)
      </details>
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **Client Version**: MacOS 1.95.10
        - **Shard-specific:**: Shard 2
    value: |
        - Client Version:
        - Shard:
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
